esphome:
  name: growatt-tcan485
  friendly_name: "MOD5000TL3-X Inverter"
  comment: "Growatt MOD 5000TL3-X Inverter via RS485 MODBUS on LiliGo TCAN485"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "REDACTED_STRING"

ota:
  - platform: esphome
    password: "REDACTED_STRING"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Growatt-Tcan485 Fallback Hotspot"
    password: "REDACTED_STRING"

captive_portal:

# Optional MQTT, I use this for EVCC smart EV charging
#mqtt:
#  broker: !secret mqtt_broker
#  port: 1883
#  username: !secret mqtt_username
#  password: !secret mqtt_password
#  discovery: false 
#  topic_prefix: "growatt_rs485/pv"  # Topic prefix for evcc

# RS485 Modbus config
uart:
  - id: uart_pv
    rx_pin: GPIO21
    tx_pin: GPIO22
    baud_rate: 9600
    parity: NONE
    stop_bits: 1

modbus:
  - uart_id: uart_pv
    id: modbus_client
    send_wait_time: 1000ms

modbus_controller:
  - id: modbus_pv
    modbus_id: modbus_client
    address: 1
    setup_priority: -10
    update_interval: 30s
    command_throttle: 1000ms

# LiliGo boilerplate
output:
  - platform: gpio
    id: ENABLE_PIN # Enable the chip
    pin:
      number: GPIO19
      inverted: true

  - platform: gpio
    id: SE_PIN # Enable autodirection
    pin:
      number: GPIO17
      inverted: true
  - platform: gpio
    id: ENABLE_5V_PIN # Enable 5V pin for RS485 chip
    pin:
      number: GPIO16
      inverted: true

# Growatt r/w setting writers
switch:
  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt On/Off"
    register_type: holding
    address: 0
    bitmask: 1 # Assuming 1 is ON, 0 is OFF
    entity_category: config
    icon: mdi:toggle-switch

number:
  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt Active Power Rate"
    register_type: holding
    address: 3
    value_type: U_WORD
    min_value: 0
    max_value: 100
    step: 1
    unit_of_measurement: "%"
    multiply: 1 
    entity_category: config
    icon: mdi:gauge
    mode: SLIDER

# Growatt read-only sensors with home assistant config
sensor:
  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt AC Output Power"
    address: 35 # Pac H (start van 32-bit waarde)
    register_count: 2
    register_type: "read"
    unit_of_measurement: W
    device_class: power
    state_class: measurement
    icon: mdi:power-plug
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt Energy Today"
    address: 53 # EAC today H / Today generate energy (high) / 0.1 kWh
    register_count: 2
    register_type: "read"
    unit_of_measurement: kWh
    device_class: energy 
    state_class: measurement 
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt Energy Total"
    address: 55 # EAC total H / Total generate energy (high) 0.1kwh
    register_count: 2
    register_type: "read"
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv 
    name: "Growatt PV1 Voltage"
    address: 3
    register_type: "read"
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    icon: mdi:sine-wave
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt PV2 Voltage"
    address: 7
    register_type: "read"
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    icon: mdi:sine-wave
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv 
    name: "Growatt PV1 Input Power" 
    address: 5 
    register_count: 2 
    register_type: "read"
    unit_of_measurement: W
    device_class: power
    state_class: measurement
    icon: mdi:flash
    value_type: U_DWORD 
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt PV2 Input Power"
    address: 9
    register_count: 2
    register_type: "read"
    unit_of_measurement: W
    device_class: power
    state_class: measurement
    icon: mdi:flash
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv 
    name: "Growatt PV1 Current"
    address: 4
    register_type: "read"
    unit_of_measurement: A
    device_class: current
    state_class: measurement
    icon: mdi:current-ac
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt PV2 Current"
    address: 8
    register_type: "read"
    unit_of_measurement: A
    device_class: current
    state_class: measurement
    icon: mdi:current-ac
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt Inverter Temperature"
    address: 93
    register_type: "read"
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt Grid Voltage"
    address: 38  # Vac1
    register_type: "read"
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    icon: mdi:sine-wave
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt Grid Frequency"
    address: 37  # Fac
    register_type: "read"
    unit_of_measurement: Hz
    device_class: frequency
    state_class: measurement
    icon: mdi:waveform
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt Fault Code"
    address: 105
    register_type: "read"
    value_type: U_WORD
    entity_category: diagnostic
    

text_sensor:
  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt Inverter Status"
    address: 0
    register_type: "read"
    raw_encode: HEXBYTES
    lambda: |-
      uint16_t value = modbus_controller::word_from_hex_str(x, 0);
      switch (value) {
        case 0: return std::string("Waiting");
        case 1: return std::string("Normal");
        case 3: return std::string("Fault");
        default: return std::string("Unknown");
      }
    icon: mdi:information