esphome:
  name: inverterlezer
  friendly_name: inverterlezer

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Inverterlezer Fallback Hotspot"
    password: ""

captive_portal:

# RS485 Modbus config
uart:
  - id: uart_pv
    tx_pin: GPIO17 #check if correct for your board/port
    rx_pin: GPIO16 #check if correct for your board/port
    baud_rate: 9600
    parity: NONE
    stop_bits: 1

modbus:
  - uart_id: uart_pv
    id: modbus_client
    send_wait_time: 1000ms

modbus_controller:
  - id: modbus_pv
    modbus_id: modbus_client
    address: 1
    setup_priority: -10
    update_interval: 30s
    command_throttle: 1000ms

# Growatt r/w setting writers
switch:
  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt On/Off"
    register_type: holding
    address: 0
    bitmask: 1 # Assuming 1 is ON, 0 is OFF
    entity_category: config
    icon: mdi:toggle-switch

number:
  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt Active Power Rate"
    register_type: holding
    address: 3
    value_type: U_WORD
    min_value: 0
    max_value: 100
    step: 1
    unit_of_measurement: "%"
    multiply: 1 
    entity_category: config
    icon: mdi:gauge
    mode: SLIDER


sensor:   
    # Growatt read-only sensors with home assistant config
  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt PV input Power"
    address: 1 # PPV H 
    register_count: 2
    register_type: "read"
    unit_of_measurement: W
    device_class: power
    state_class: measurement
    icon: mdi:flash
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt AC Output Power"
    address: 35 # Pac H (start van 32-bit waarde)
    register_count: 2
    register_type: "read"
    unit_of_measurement: W
    device_class: power
    state_class: measurement
    icon: mdi:power-plug
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt AC Energy Today"
    address: 53 # EAC today H / Today generate energy (high) / 0.1 kWh
    register_count: 2
    register_type: "read"
    unit_of_measurement: kWh
    device_class: energy 
    state_class: measurement 
    icon: mdi:power-plug
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt AC Energy Total"
    address: 55 # EAC total H / Total generate energy (high) 0.1kwh
    register_count: 2
    register_type: "read"
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    icon: mdi:power-plug
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt PV1 Energy Today"
    address: 59 # EPV1 today H / PV1 Energy today(high) / 0.1 kWh
    register_count: 2
    register_type: "read"
    unit_of_measurement: kWh
    device_class: energy 
    state_class: measurement 
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt PV1 Energy Total"
    address: 61 # EPV1 total H / PV1 Energy total(high) 0.1kwh
    register_count: 2
    register_type: "read"
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt PV2 Energy Today"
    address: 63 # EPV2 today H / PV2 Energy today(high) / 0.1 kWh
    register_count: 2
    register_type: "read"
    unit_of_measurement: kWh
    device_class: energy 
    state_class: measurement 
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt PV2 Energy Total"
    address: 65 # EPV2 total H / PV2 Energy total(high) 0.1kwh
    register_count: 2
    register_type: "read"
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt PV Energy Total"
    address: 91 # EPV total H / PV Energy total(high) 0.1kwh
    register_count: 2
    register_type: "read"
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv 
    name: "Growatt PV1 Voltage"
    address: 3
    register_type: "read"
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    icon: mdi:sine-wave
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt PV2 Voltage"
    address: 7
    register_type: "read"
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    icon: mdi:sine-wave
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv 
    name: "Growatt PV1 Input Power" 
    address: 5 
    register_count: 2 
    register_type: "read"
    unit_of_measurement: W
    device_class: power
    state_class: measurement
    icon: mdi:flash
    value_type: U_DWORD 
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt PV2 Input Power"
    address: 9
    register_count: 2
    register_type: "read"
    unit_of_measurement: W
    device_class: power
    state_class: measurement
    icon: mdi:flash
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv 
    name: "Growatt PV1 Current"
    address: 4
    register_type: "read"
    unit_of_measurement: A
    device_class: current
    state_class: measurement
    icon: mdi:current-ac
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt PV2 Current"
    address: 8
    register_type: "read"
    unit_of_measurement: A
    device_class: current
    state_class: measurement
    icon: mdi:current-ac
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt Inverter Temperature"
    address: 93
    register_type: "read"
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt Grid Voltage"
    address: 38  # Vac1
    register_type: "read"
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
    icon: mdi:sine-wave
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt Grid Frequency"
    address: 37  # Fac
    register_type: "read"
    unit_of_measurement: Hz
    device_class: frequency
    state_class: measurement
    icon: mdi:waveform
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt Fault Code"
    address: 105
    register_type: "read"
    value_type: U_WORD
    entity_category: diagnostic

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt Battery State-of-charge"
    address: 3171  # SOC
    register_type: "read"
    unit_of_measurement: "%"
    device_class: battery
    state_class: measurement
    icon: mdi:battery
    value_type: U_WORD
    accuracy_decimals: 0
    filters:
      - multiply: 1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt Battery Discharged Today"
    address: 3125 # / 0.1 kWh
    register_count: 2
    register_type: "read"
    unit_of_measurement: kWh
    device_class: energy 
    state_class: measurement 
    icon: mdi:battery-arrow-down
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt Battery Discharged Total"
    address: 3127 # 0.1kwh
    register_count: 2
    register_type: "read"
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    icon: mdi:battery-arrow-down
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt Battery Charged Today"
    address: 3129 # / 0.1 kWh
    register_count: 2
    register_type: "read"
    unit_of_measurement: kWh
    device_class: energy 
    state_class: measurement 
    icon: mdi:battery-arrow-up
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt Battery Charged Total"
    address: 3131 # 0.1kwh
    register_count: 2
    register_type: "read"
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    icon: mdi:battery-arrow-up
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1    

  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt Battery Discharge Power"
    address: 3178 # 0.1 W
    register_count: 2
    register_type: "read"
    unit_of_measurement: W
    device_class: power
    state_class: measurement
    icon: mdi:battery-arrow-down
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1 
    
  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt Battery Charge Power"
    address: 3180 # / 0.1 W
    register_count: 2
    register_type: "read"
    unit_of_measurement: W
    device_class: power 
    state_class: measurement 
    icon: mdi:battery-arrow-up
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

text_sensor:
  - platform: modbus_controller
    modbus_controller_id: modbus_pv
    name: "Growatt Inverter Status"
    address: 0
    register_type: "read"
    raw_encode: HEXBYTES
    lambda: |-
      uint16_t value = modbus_controller::word_from_hex_str(x, 0);
      switch (value) {
        case 0: return std::string("Waiting");
        case 1: return std::string("Normal");
        case 3: return std::string("Fault");
        default: return std::string("Unknown");
      }
    icon: mdi:information
